import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql, useQuery } from '@apollo/client'
import Header from '../components/Layouts/Header'

const allInvestmentQuery = gql `
query{
  investments {
    title
    imageUrl
    category
    description
    amount

  }
}
`
export default function Home() {
  const { data, loading, error} = useQuery(allInvestmentQuery)
  
  if (loading) return <p>Loading...</p>
  if (error) return <p className={styles.error}>Oh no... {error.message}</p>
  
  return (
    <div >
      <Head>
        <title>Isidore Housing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <h1>
          Welcome to Isidore Housing investment
        </h1>
        {/* <Link href="/api/auth/login" >Login</Link> */}

        <ul className={styles.grid}>
        {data.investments.map((investment: any)=>{
          return (
          
            <li className={styles.card} key={investment.id}>
              <Image src={investment.imageUrl} loading='lazy'  alt='housing' width={250} height={250} />
              <h4>{investment.title}</h4>
              <p>{investment.category}</p>
              <p>{investment.description}</p>
              <p><strong>${investment.amount}</strong></p>
            </li>

          )}
        )}
        
        
        </ul>
      </main>

   
    </div>
  )
}
